Handle multiple hostnames/fqdns, fixes #4

diff --git a/install.yaml b/install.yaml
--- a/install.yaml
+++ b/install.yaml
@@ -5,3 +5,24 @@ project_files:
 - docker-compose.varnish.yaml
 - varnish
 
+post_install_actions:
+  - |
+    #ddev-nodisplay
+    if [ -f .ddev/docker-compose.varnish-extras.yaml ] && ! grep '#ddev-generated' .ddev/config.varnish-extras.yaml; then
+      echo "Existing docker-compose.varnish-extras.yaml does not have #ddev-generated, so can't be updated"
+    exit 2
+    fi
+  - |
+    #ddev-nodisplay
+    cat  <<-END >docker-compose.varnish-extras.yaml
+    #ddev-generated
+    # This is the second half of the trick that puts varnish "in front of" the web
+    # container, just by switching the names.
+    services:
+      web:
+        environment:
+        - VIRTUAL_HOST=novarnish.{{ join ",novarnish." (concat .configyaml.additional_hostnames .configyaml.additional_fqdns)}}
+    END
+
+yaml_read_files:
+  configyaml: .ddev/config.yaml
