Handle multiple hostnames/fqdns, fixes #4 (#9)
* Handle multiple hostnames/fqdns, fixes #4

* Add extra hostname to test, use homebrew action for github

* Disable install from release until this goes in

* Add some output back into the test

* Minor simplification of github tests

* Handle novarnish usernames properly

* Revise README with information about improved additional_hostnames, additional_fqdns handling.

* Modify tests to check additional_hostnames, additional_fqdns too.

Co-authored-by: Johan Du Bois <me@johandubois.com>

diff --git a/install.yaml b/install.yaml
--- a/install.yaml
+++ b/install.yaml
@@ -5,3 +5,33 @@ project_files:
 - docker-compose.varnish.yaml
 - varnish
 
+post_install_actions:
+  - |
+    #ddev-nodisplay
+    if [ -f .ddev/docker-compose.varnish-extras.yaml ] && ! grep '#ddev-generated' .ddev/config.varnish-extras.yaml; then
+      echo "Existing docker-compose.varnish-extras.yaml does not have #ddev-generated, so can't be updated"
+    exit 2
+    fi
+  - |
+    #ddev-nodisplay
+    cat  <<-END >docker-compose.varnish-extras.yaml
+    #ddev-generated
+    # This is the second half of the trick that puts varnish "in front of" the web
+    # container, just by switching the names.
+    {{ $project_tld := "ddev.site" }}
+    {{ if .DdevGlobalConfig.project_tld }}{{ $project_tld = .DdevGlobalConfig.project_tld }}{{ end }}
+    {{ if .DdevProjectConfig.project_tld }}{{ $project_tld = .DdevProjectConfig.project_tld }} {{ end }}
+    {{ $novarnish_hostnames := print "novarnish." .DdevProjectConfig.name "." $project_tld  }}
+    {{ $sep := print "." $project_tld ",novarnish." }}
+    {{ if .DdevProjectConfig.additional_hostnames }}
+    {{ $novarnish_hostnames = print $novarnish_hostnames "," "novarnish." (.DdevProjectConfig.additional_hostnames | join $sep) "." $project_tld }}
+    {{ end }}
+    {{ if .DdevProjectConfig.additional_fqdns }}
+    {{ $novarnish_hostnames = print $novarnish_hostnames "," "novarnish." ( .DdevProjectConfig.additional_fqdns | join ",novarnish." )   }}
+    {{ end }}
+    services:
+      web:
+        environment:
+        - VIRTUAL_HOST={{ $novarnish_hostnames }}
+
+    END
